esp_toml_version = 1.0

firmware_images_url = "https://raw.githubusercontent.com/anishadhikaari/ESP32_TEST_FERMWARE/main/"

supported_apps = ["my_secret_app"]

[my_secret_app]
chipsets = ["ESP32"]
image.esp32 = "FOTA_GIT_ANI.merged.bin"
description = "Anishs Secret Firmware"
