supported_apps = ["my_secret_app"]

[app:my_secret_app]
name = "Anishs Secret Firmware"
chipset = "ESP32"

[[app:my_secret_app.images]]
address = "0x0"
path = "https://raw.githubusercontent.com/anishadhikaari/ESP32_TEST_FERMWARE/main/FOTA_GIT_ANI.ino.bin"
